


GET  http://localhost:8000/api/v1/deletOTPS
###

POST http://localhost:8000/api/v1/phone
content-type: application/json

{
    "phone": "+260971196736"
}

###
POST http://localhost:8000/api/v1/otpverification
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InBob25lIjoiKzI2MDk3MTE5NjczNiJ9LCJpYXQiOjE2NDMwMzM2NTEsImV4cCI6MTY0MzAzMzk1MX0.ac6DL2wyXRZG6o_7kiSVNvo5RDQgXWjnmv2pVmkWOaY
content-type: application/json

{
    "otp":"486526"
}