GET http://localhost:5000/

###

POST http://localhost:5000/api/v1/users/signup
content-type: application/json

{
    "phoneNumber": "0971196736"
}

###
POST http://localhost:5000/api/v1/users/signup/verify
content-type: application/json

{
    
     "phoneNumber": "0971196736",
    "otp": "833260"
}
